name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/1 * * *'
jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit Changes
        run: |
          curl https://github.com/TheSamsungFreak/PL_TV_M3U/blob/main/TV_PlusX_TV.m3u	 > list.m3u
          curl https://github.com/TheSamsungFreak/PL_TV_M3U/blob/main/TV_Local_Channels.m3u	 > list.m3u
          curl https://raw.githubusercontent.com/TheSamsungFreak/PL_TV_M3U/main/KSW_TV.m3u | grep -iv -E 'www.ast.tv|adultiptv|redtraffic|jasminchannel|group-title="XXX"' >> list.m3u
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add list.m3u
          git diff-index --quiet HEAD || git commit -m "[Bot] Update the list"
          git pull
          git push
