name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/1 * * *'
jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Commit Changes
        run: |
          curl https://raw.githubusercontent.com/Winges4k/livestreams/main/EMARATTV-EXTRA.m3ux	 > list.m3u
          curl http://m3u4u.com/m3u/m/7w51g8x2447awkn8xknr	 > list.m3u
          curl https://iptv-org.github.io/iptv/countries/be.m3ux | grep -iv -E 'www.ast.tv|adultiptv|redtraffic|jasminchannel|group-title="XXX"' >> list.m3u
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add list.m3u
          git diff-index --quiet HEAD || git commit -m "[Bot] Update the list"
          git pull
          git push
